name: Update README

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use git-auto-commit-action
      id: "auto-commit-action"
      uses: ./

    - name: "changes detected"
      run: "echo \"Changes detected\""

