name: Update README

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "changes detected"
      run: "echo \"Changes detected\""

