name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "./.github/update-readme.config.yml"
        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    

          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

